// Generated by gonvex dev. Do not edit.

export const api = {
  "tasks.randomizeStatusPriority": { kind: "mutation", path: "tasks.randomizeStatusPriority" },
  "tasks.grid": { kind: "liveGrid", path: "tasks.grid" },
  "files.delete": { kind: "mutation", path: "files.delete" },
  "files.createUploadUrl": { kind: "mutation", path: "files.createUploadUrl" },
  "files.getUrl": { kind: "query", path: "files.getUrl" },
  "files.getMetadata": { kind: "query", path: "files.getMetadata" },
  "tasks.list": { kind: "query", path: "tasks.list" },
  "tasks.create": { kind: "mutation", path: "tasks.create" },
} as const;

export type Api = typeof api;
