// Generated by gonvex dev. Do not edit.

export const controlPlane = {
  scope: "control-plane",
  tables: {
  },
} as const;

// Compatibility alias for the former landlord scope.
export const landlord = controlPlane;

export const tenant = {
  scope: "tenant",
  tables: {
    dashboard_demo_files: {
      columns: {
        content_type: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
        key: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        size: {
          nullable: true,
          primaryKey: false,
          type: "int64",
        },
      },
      indexes: {
        by_key: {
          columns: ["key"],
          unique: true,
        },
      },
    },
    dashboard_demo_tasks: {
      columns: {
        all_user_avatar_urls: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        all_user_names: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        approval_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        asset_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        assignee: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        assignee_avatar_urls: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        assignee_ids: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        assignee_names: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        attachment_count: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        audience: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        audience_team_ids: {
          nullable: true,
          primaryKey: false,
          type: "json",
        },
        audience_user_ids: {
          nullable: true,
          primaryKey: false,
          type: "json",
        },
        category_color: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        category_icon: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        category_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        category_name: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        completed: {
          nullable: true,
          primaryKey: false,
          type: "bool",
        },
        completed_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        created_by: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        deleted_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        description: {
          nullable: true,
          primaryKey: false,
          type: "text",
        },
        due_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        due_date: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        estimate_minutes: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        expected_duration: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        first_viewed_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        flag_color: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        form_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
        label: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        latitude: {
          nullable: true,
          primaryKey: false,
          type: "float64",
        },
        longitude: {
          nullable: true,
          primaryKey: false,
          type: "float64",
        },
        name: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        notes_count: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        occurrence_date: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        pg_id: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        priority: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        priority_color: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        priority_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        priority_name: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        progress: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        project: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        recurrence_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        reported_by_team_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        reported_by_user_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        requires_acknowledgment: {
          nullable: true,
          primaryKey: false,
          type: "bool",
        },
        requires_signature: {
          nullable: true,
          primaryKey: false,
          type: "bool",
        },
        row_hash: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        sla_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        sla_paused_duration: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        sla_resolution_deadline: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        sla_resolved_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        sla_responded_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        sla_response_deadline: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        sla_started_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        spot_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        spot_name: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        start_date: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        status: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        status_action: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        status_color: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        status_icon: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        status_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        status_initial: {
          nullable: true,
          primaryKey: false,
          type: "bool",
        },
        status_name: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        status_working_animation: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        tag_colors: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        tag_names: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        team_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        template_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        tenant_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        title: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        updated_at: {
          nullable: true,
          primaryKey: false,
          type: "time",
        },
        view_count: {
          nullable: true,
          primaryKey: false,
          type: "int",
        },
        workplan_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        workplan_instance_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        workplan_item_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        workspace_id: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
        workspace_name: {
          nullable: true,
          primaryKey: false,
          type: "string",
        },
      },
      indexes: {
        by_active_created_at: {
          columns: ["deleted_at","created_at","id"],
          unique: false,
        },
        by_active_pg_id: {
          columns: ["deleted_at","pg_id","id"],
          unique: false,
        },
        by_assignee: {
          columns: ["assignee"],
          unique: false,
        },
        by_assignee_created_at: {
          columns: ["tenant_id","assignee","deleted_at","created_at","id"],
          unique: false,
        },
        by_assignee_names: {
          columns: ["assignee_names"],
          unique: false,
        },
        by_category: {
          columns: ["tenant_id","category_id"],
          unique: false,
        },
        by_created_at: {
          columns: ["created_at"],
          unique: false,
        },
        by_created_at_id: {
          columns: ["created_at","id"],
          unique: false,
        },
        by_due_at: {
          columns: ["due_at"],
          unique: false,
        },
        by_due_created_at: {
          columns: ["tenant_id","due_at","deleted_at","created_at","id"],
          unique: false,
        },
        by_due_date: {
          columns: ["due_date"],
          unique: false,
        },
        by_flag_color: {
          columns: ["flag_color"],
          unique: false,
        },
        by_name: {
          columns: ["name"],
          unique: false,
        },
        by_pg_id: {
          columns: ["pg_id"],
          unique: false,
        },
        by_priority: {
          columns: ["priority"],
          unique: false,
        },
        by_priority_created_at: {
          columns: ["tenant_id","priority_id","deleted_at","created_at","id"],
          unique: false,
        },
        by_priority_id: {
          columns: ["tenant_id","priority_id"],
          unique: false,
        },
        by_priority_name: {
          columns: ["priority_name"],
          unique: false,
        },
        by_project: {
          columns: ["project"],
          unique: false,
        },
        by_spot: {
          columns: ["tenant_id","spot_id"],
          unique: false,
        },
        by_spot_name: {
          columns: ["spot_name"],
          unique: false,
        },
        by_status: {
          columns: ["status"],
          unique: false,
        },
        by_status_created_at: {
          columns: ["tenant_id","status_id","deleted_at","created_at","id"],
          unique: false,
        },
        by_status_id: {
          columns: ["tenant_id","status_id"],
          unique: false,
        },
        by_status_name: {
          columns: ["status_name"],
          unique: false,
        },
        by_team: {
          columns: ["tenant_id","team_id"],
          unique: false,
        },
        by_tenant_pg_id: {
          columns: ["tenant_id","pg_id"],
          unique: false,
        },
        by_updated_at: {
          columns: ["updated_at"],
          unique: false,
        },
        by_workspace: {
          columns: ["tenant_id","workspace_id"],
          unique: false,
        },
        by_workspace_created_at: {
          columns: ["tenant_id","workspace_id","deleted_at","created_at","id"],
          unique: false,
        },
        by_workspace_name: {
          columns: ["workspace_name"],
          unique: false,
        },
        by_workspace_pg_id: {
          columns: ["tenant_id","workspace_id","deleted_at","pg_id","id"],
          unique: false,
        },
        description_trgm: {
          columns: ["description"],
          kind: "trigram",
          unique: false,
        },
        name_trgm: {
          columns: ["name"],
          kind: "trigram",
          unique: false,
        },
        search_text_trgm: {
          columns: ["name","title","description","status","priority","assignee","project","label","flag_color"],
          kind: "trigram",
          unique: false,
        },
        title_trgm: {
          columns: ["title"],
          kind: "trigram",
          unique: false,
        },
      },
    },
  },
} as const;

export const tables = tenant.tables;

export const schema = {
  controlPlane,
  landlord,
  tenant,
  tables,
} as const;

export type LandlordTableName = keyof typeof landlord.tables;
export type TenantTableName = keyof typeof tenant.tables;
export type TableName = TenantTableName;
