root = "."
tmp_dir = "tmp/air"

[build]
  cmd = "go build -o ./tmp/air/gonvex-runtime.exe ./server/cmd/gonvex-runtime"
  bin = "./tmp/air/gonvex-runtime.exe"
  delay = 1000
  exclude_dir = ["apps", "node_modules", "tmp", ".next", "dist"]
  include_ext = ["go", "env"]
  kill_delay = "500ms"
  log = "air-build.log"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = false
