package gonvextest

import "github.com/gonvex/gonvex/pkg/gonvex"

func Schema(s *gonvex.Schema) {
	s.Table("tasks", func(t *gonvex.Table) {
		t.ID("id")
		t.String("tenant_id", gonvex.Nullable)
		t.Int("pg_id", gonvex.Nullable)
		t.String("name", gonvex.Nullable)
		t.String("title")
		t.String("status")
		t.Text("description", gonvex.Nullable)
		t.String("audience", gonvex.Nullable)
		t.JSON("audience_user_ids", gonvex.Nullable)
		t.JSON("audience_team_ids", gonvex.Nullable)
		t.Bool("requires_acknowledgment", gonvex.Nullable)
		t.String("workspace_id", gonvex.Nullable)
		t.String("category_id", gonvex.Nullable)
		t.String("team_id", gonvex.Nullable)
		t.String("template_id", gonvex.Nullable)
		t.String("spot_id", gonvex.Nullable)
		t.String("status_id", gonvex.Nullable)
		t.String("priority_id", gonvex.Nullable)
		t.String("status_name", gonvex.Nullable)
		t.String("status_color", gonvex.Nullable)
		t.String("status_action", gonvex.Nullable)
		t.String("status_icon", gonvex.Nullable)
		t.String("status_working_animation", gonvex.Nullable)
		t.Bool("status_initial", gonvex.Nullable)
		t.String("priority_name", gonvex.Nullable)
		t.String("priority_color", gonvex.Nullable)
		t.String("category_name", gonvex.Nullable)
		t.String("category_icon", gonvex.Nullable)
		t.String("category_color", gonvex.Nullable)
		t.String("tag_names", gonvex.Nullable)
		t.String("tag_colors", gonvex.Nullable)
		t.Int("attachment_count", gonvex.Nullable)
		t.Int("view_count", gonvex.Nullable)
		t.String("sla_id", gonvex.Nullable)
		t.String("approval_id", gonvex.Nullable)
		t.String("form_id", gonvex.Nullable)
		t.Bool("requires_signature", gonvex.Nullable)
		t.String("asset_id", gonvex.Nullable)
		t.String("created_by", gonvex.Nullable)
		t.String("reported_by_team_id", gonvex.Nullable)
		t.String("reported_by_user_id", gonvex.Nullable)
		t.String("recurrence_id", gonvex.Nullable)
		t.String("workplan_id", gonvex.Nullable)
		t.String("workplan_item_id", gonvex.Nullable)
		t.String("workplan_instance_id", gonvex.Nullable)
		t.String("occurrence_date", gonvex.Nullable)
		t.Int("expected_duration", gonvex.Nullable)
		t.String("flag_color", gonvex.Nullable)
		t.String("spot_name", gonvex.Nullable)
		t.String("workspace_name", gonvex.Nullable)
		t.String("assignee_names", gonvex.Nullable)
		t.String("assignee_ids", gonvex.Nullable)
		t.String("assignee_avatar_urls", gonvex.Nullable)
		t.String("all_user_names", gonvex.Nullable)
		t.String("all_user_avatar_urls", gonvex.Nullable)
		t.Int("notes_count", gonvex.Nullable)
		t.Time("sla_started_at", gonvex.Nullable)
		t.Time("sla_response_deadline", gonvex.Nullable)
		t.Time("sla_resolution_deadline", gonvex.Nullable)
		t.Time("sla_responded_at", gonvex.Nullable)
		t.Time("sla_resolved_at", gonvex.Nullable)
		t.Int("sla_paused_duration", gonvex.Nullable)
		t.Time("due_date", gonvex.Nullable)
		t.Time("start_date", gonvex.Nullable)
		t.Time("completed_at", gonvex.Nullable)
		t.Float64("latitude", gonvex.Nullable)
		t.Float64("longitude", gonvex.Nullable)
		t.Time("first_viewed_at", gonvex.Nullable)
		t.Time("deleted_at", gonvex.Nullable)
		t.String("row_hash", gonvex.Nullable)
		t.String("priority", gonvex.Nullable)
		t.String("assignee", gonvex.Nullable)
		t.String("project", gonvex.Nullable)
		t.String("label", gonvex.Nullable)
		t.Time("due_at", gonvex.Nullable)
		t.Bool("completed", gonvex.Nullable)
		t.Int("estimate_minutes", gonvex.Nullable)
		t.Int("progress", gonvex.Nullable)
		t.Time("created_at")
		t.Time("updated_at", gonvex.Nullable)
		t.Index("by_status", "status")
		t.Index("by_pg_id", "pg_id")
		t.Index("by_name", "name")
		t.Index("by_tenant_pg_id", "tenant_id", "pg_id")
		t.Index("by_workspace", "tenant_id", "workspace_id")
		t.Index("by_status_id", "tenant_id", "status_id")
		t.Index("by_category", "tenant_id", "category_id")
		t.Index("by_priority_id", "tenant_id", "priority_id")
		t.Index("by_status_name", "status_name")
		t.Index("by_priority_name", "priority_name")
		t.Index("by_team", "tenant_id", "team_id")
		t.Index("by_spot", "tenant_id", "spot_id")
		t.Index("by_spot_name", "spot_name")
		t.Index("by_workspace_name", "workspace_name")
		t.Index("by_assignee_names", "assignee_names")
		t.Index("by_flag_color", "flag_color")
		t.Index("by_priority", "priority")
		t.Index("by_assignee", "assignee")
		t.Index("by_project", "project")
		t.Index("by_due_date", "due_date")
		t.Index("by_due_at", "due_at")
		t.Index("by_created_at", "created_at")
		t.Index("by_created_at_id", "created_at", "id")
		t.Index("by_updated_at", "updated_at")
	})

	s.Table("files", func(t *gonvex.Table) {
		t.ID("id")
		t.String("key")
		t.String("content_type", gonvex.Nullable)
		t.Int64("size", gonvex.Nullable)
		t.Time("created_at")
		t.UniqueIndex("by_key", "key")
	})
}
