// Generated by gonvex dev. Do not edit.

export const api = {
  messages: {
    list: { kind: "query", path: "messages.list" },
    send: { kind: "mutation", path: "messages.send" },
  },
} as const;

export const internal = api;
export type Api = typeof api;
