// Generated by gonvex dev. Do not edit.

export const api = {
  "messages.list": { kind: "query", path: "messages.list" },
  "messages.send": { kind: "mutation", path: "messages.send" },
} as const;

export type Api = typeof api;
