// Generated by gonvex dev. Do not edit.

export const schema = {
  tables: {
    messages: {
      columns: {
        author: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        body: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
      },
      indexes: {
        by_created_at: {
          columns: ["created_at"],
          unique: false,
        },
      },
    },
  },
  controlPlaneTables: {},
  landlordTables: {},
  tenantTables: {
    messages: {
      columns: {
        author: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        body: {
          nullable: false,
          primaryKey: false,
          type: "string",
        },
        created_at: {
          nullable: false,
          primaryKey: false,
          type: "time",
        },
        id: {
          nullable: false,
          primaryKey: true,
          type: "id",
        },
      },
      indexes: {
        by_created_at: {
          columns: ["created_at"],
          unique: false,
        },
      },
    },
  },
} as const;

export const controlPlane = { tables: schema.controlPlaneTables ?? {} } as const;
export const landlord = controlPlane;
export const tenant = { tables: schema.tenantTables ?? schema.tables } as const;
export const tables = tenant.tables;
