// Generated by gonvex dev. Do not edit.

export const controlPlane = {
  scope: "control-plane",
  tables: {
  },
} as const;

export const tenant = {
  scope: "tenant",
  tables: {
  },
} as const;

export const tables = tenant.tables;

export const schema = {
  controlPlane,
  tenant,
  tables,
} as const;

export type ControlPlaneTableName = keyof typeof controlPlane.tables;
export type TenantTableName = keyof typeof tenant.tables;
export type TableName = TenantTableName;
