// Generated by gonvex dev. Do not edit.

export const schema = {
  scope: "tenant",
  tables: {
  },
} as const;

export const tenant = schema;
export const tables = schema.tables;

export type TableName = keyof typeof tables;
