// Generated by gonvex dev. Do not edit.

export const scope = "tenant" as const;

export const tables = {
  messages: {
    columns: {
      author: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      body: {
        nullable: false,
        primaryKey: false,
        type: "string",
      },
      created_at: {
        nullable: false,
        primaryKey: false,
        type: "time",
      },
      id: {
        nullable: false,
        primaryKey: true,
        type: "id",
      },
    },
    indexes: {
      by_created_at: {
        columns: ["created_at"],
        unique: false,
      },
    },
  },
} as const;

export type TableName = keyof typeof tables;
