// Generated by gonvex dev. Do not edit.

export const schema = {
  scope: "control-plane",
  tables: {
  },
} as const;

export const controlPlane = schema;
export const tables = schema.tables;

export type TableName = keyof typeof tables;
