// Generated by gonvex dev. Do not edit.
export const schema = {
  tables: {},
} as const;

export const controlPlane = schema;
export const landlord = controlPlane;
export const tables = schema.tables;
